# Generated by Django 6.0.5 on 2026-05-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bosses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('optional', models.BooleanField(default=False)),
                ('difficulty', models.CharField(max_length=50)),
                ('total_health', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharmNotches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('required_boss', models.CharField(max_length=100)),
                ('required_equipment', models.CharField(max_length=100)),
                ('required_ability', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Charms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('required_ability', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Colloseum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('total_rounds', models.IntegerField()),
                ('rewards', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dreamers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('required_bosses', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('required_resource', models.CharField(max_length=100)),
                ('required_ability', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('required_ability', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaskShards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('required_boss', models.CharField(max_length=100)),
                ('required_equipment', models.CharField(max_length=100)),
                ('required_ability', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pantheons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('total_challenges', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VesselFragments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('required_boss', models.CharField(max_length=100)),
                ('required_equipment', models.CharField(max_length=100)),
                ('required_ability', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
