# Generated by Django 6.0.5 on 2026-05-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingspass', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bosses',
            new_name='Boss',
        ),
        migrations.RenameModel(
            old_name='Charms',
            new_name='Charm',
        ),
        migrations.RenameModel(
            old_name='CharmNotches',
            new_name='CharmNotch',
        ),
        migrations.RenameModel(
            old_name='Dreamers',
            new_name='Dreamer',
        ),
        migrations.RenameModel(
            old_name='Grubs',
            new_name='Grub',
        ),
        migrations.RenameModel(
            old_name='MaskShards',
            new_name='MaskShard',
        ),
        migrations.RenameModel(
            old_name='Pantheons',
            new_name='Pantheon',
        ),
        migrations.RenameModel(
            old_name='VesselFragments',
            new_name='VesselFragment',
        ),
    ]
